/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package src;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.JOptionPane;

/**
 *
 * @author Allen
 */
public class addproduct extends javax.swing.JFrame {

    /**
     * Creates new form addproduct
     */
    public int productIdCounter = 1;

    public addproduct() {
        initComponents();
    }

    private void saveProduct(String productField, int quantityField, double priceField) {
        int productId;

        try ( BufferedReader reader = new BufferedReader(new FileReader(productStorage.getfilepath()))) {
            String line;
            int maxId = 0;
            while ((line = reader.readLine()) != null) {
                String[] rowData = line.split(",");
                int id = Integer.parseInt(rowData[0]);
                if (id > maxId) {
                    maxId = id;
                }
            }
            productIdCounter = maxId + 1;
        } catch (IOException e) {
            e.printStackTrace();
        }

        productId = productIdCounter++;

        try ( BufferedWriter writer = new BufferedWriter(new FileWriter(productStorage.getfilepath(), true))) {
            writer.write(productId + "," + productField + "," + quantityField + "," + priceField);
            writer.newLine();
        } catch (IOException e) {
            e.printStackTrace();
        }

        productStorage.products(productId + "," + productField + "," + quantityField + "," + priceField);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        addproductlabel = new javax.swing.JLabel();
        productnamelabel = new javax.swing.JLabel();
        productfield = new javax.swing.JTextField();
        pricelabel = new javax.swing.JLabel();
        pricefield = new javax.swing.JTextField();
        quantitylabel = new javax.swing.JLabel();
        subincrement = new javax.swing.JButton();
        quantityfield = new javax.swing.JTextField();
        addincrement = new javax.swing.JButton();
        addbutton = new javax.swing.JButton();
        backbutton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(500, 400));
        setPreferredSize(new java.awt.Dimension(500, 400));

        addproductlabel.setFont(new java.awt.Font("Helvetica Neue", 0, 48)); // NOI18N
        addproductlabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        addproductlabel.setText("Add Product");

        productnamelabel.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        productnamelabel.setText("Product Name:");

        productfield.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N

        pricelabel.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        pricelabel.setText("Price:");

        pricefield.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N

        quantitylabel.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        quantitylabel.setText("Quantity:");

        subincrement.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        subincrement.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rsc/minus.png"))); // NOI18N
        subincrement.setBorderPainted(false);
        subincrement.setContentAreaFilled(false);
        subincrement.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        subincrement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subincrementActionPerformed(evt);
            }
        });

        quantityfield.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        quantityfield.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        quantityfield.setText("0");

        addincrement.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        addincrement.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rsc/plus.png"))); // NOI18N
        addincrement.setBorderPainted(false);
        addincrement.setContentAreaFilled(false);
        addincrement.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        addincrement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addincrementActionPerformed(evt);
            }
        });

        addbutton.setText("ADD");
        addbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addbuttonActionPerformed(evt);
            }
        });

        backbutton.setText("BACK");
        backbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbuttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(subincrement, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(quantityfield, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(addincrement, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(quantitylabel, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(addbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(backbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(pricelabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(productfield, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                        .addComponent(productnamelabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(addproductlabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pricefield, javax.swing.GroupLayout.Alignment.LEADING)))
                .addContainerGap(100, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(addproductlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(productnamelabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(productfield, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pricelabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pricefield, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(quantitylabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(subincrement, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(quantityfield, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(addincrement, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(backbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(75, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void subincrementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subincrementActionPerformed
        // TODO add your handling code here:
        String currentText = quantityfield.getText();
        if (!currentText.isEmpty()) {
            try {
                int currentValue = Integer.parseInt(currentText);
                int newValue = currentValue - 1;

                quantityfield.setText(String.valueOf(newValue));

            } catch (NumberFormatException e) {
                e.printStackTrace();
            }
        } else {
        }
    }//GEN-LAST:event_subincrementActionPerformed

    private void addincrementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addincrementActionPerformed
        // TODO add your handling code here:
        String currentText = quantityfield.getText();
        if (!currentText.isEmpty()) {
            try {
                int currentValue = Integer.parseInt(currentText);
                int newValue = currentValue + 1;

                quantityfield.setText(String.valueOf(newValue));

            } catch (NumberFormatException e) {
                e.printStackTrace();
            }
        } else {
        }
    }//GEN-LAST:event_addincrementActionPerformed

    private void addbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addbuttonActionPerformed
        // TODO add your handling code here:
        String productField = productfield.getText();
        int quantityField = Integer.parseInt(quantityfield.getText());
        double priceField = Double.parseDouble(pricefield.getText());

        saveProduct(productField, quantityField, priceField);
        JOptionPane.showMessageDialog(null, "Product Added", "Add Status", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_addbuttonActionPerformed

    private void backbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbuttonActionPerformed
        // TODO add your handling code here:
        dispose();
        dashboard dashboard = new dashboard();
        dashboard.addproductbutton.setEnabled(true);
        dashboard.addaccountbutton.setEnabled(true);
        dashboard.setVisible(true);
    }//GEN-LAST:event_backbuttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addproduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addproduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addproduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addproduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addproduct().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addbutton;
    private javax.swing.JButton addincrement;
    private javax.swing.JLabel addproductlabel;
    private javax.swing.JButton backbutton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField pricefield;
    private javax.swing.JLabel pricelabel;
    private javax.swing.JTextField productfield;
    private javax.swing.JLabel productnamelabel;
    private javax.swing.JTextField quantityfield;
    private javax.swing.JLabel quantitylabel;
    private javax.swing.JButton subincrement;
    // End of variables declaration//GEN-END:variables
}
