/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package src;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Allen
 */
public class pos extends javax.swing.JFrame {

    /**
     * Creates new form pos
     */
    public JTextField textfield;

    public pos() {
        initComponents();
        retrieveData();
    }

    void retrieveData() {
        DefaultTableModel model = (DefaultTableModel) inventoryTable.getModel();

        String filePath = productStorage.getfilepath();

        try ( BufferedReader br = new BufferedReader(new FileReader(filePath))) {
            String line;
            while ((line = br.readLine()) != null) {
                String[] rowData = line.split(",");

                model.addRow(rowData);
            }
        } catch (IOException e) {
            e.printStackTrace();
        }
    }

    private double calculateTotal(String productName, int quantity, double price) {
        double total = 0;

        try ( BufferedReader reader = new BufferedReader(new FileReader("data.txt"))) {
            String line;
            while ((line = reader.readLine()) != null) {
                String[] rowData = line.split(",");
                String name = rowData[1].trim();
                int storedQuantity = Integer.parseInt(rowData[2]);
                double storedPrice = Double.parseDouble(rowData[3]);

                if (name.equalsIgnoreCase(productName)) {
                    total += quantity * price;
                }
            }
        } catch (IOException ex) {
            ex.printStackTrace();
        }

        return total;
    }

    private void updateProductQuantity(String productName, int quantity) {
        //String databaseFilePath = "path/to/your/database/file.txt";

        try ( BufferedReader reader = new BufferedReader(new FileReader("/Users/allen/NetBeansProjects/pos/src/db/products.txt"))) {
            StringBuilder fileContent = new StringBuilder();
            String line;

            // Read the file line by line
            while ((line = reader.readLine()) != null) {
                String[] parts = line.split(",");

                // Check if the current line corresponds to the product to be updated
                if (parts.length >= 2 && parts[0].equals(productName)) {
                    int currentQuantity = Integer.parseInt(parts[1]);
                    int updatedQuantity = currentQuantity - quantity;
                    parts[1] = String.valueOf(updatedQuantity);
                }

                // Append the updated line to the file content
                fileContent.append(String.join(",", parts)).append(System.lineSeparator());
            }

            // Save the updated content back to the file
            try ( BufferedWriter writer = new BufferedWriter(new FileWriter("/Users/allen/NetBeansProjects/pos/src/db/products.txt"))) {
                writer.write(fileContent.toString());
            }
        } catch (IOException e) {
            // Handle the exception appropriately
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        overviewpanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        itemsOverview = new javax.swing.JTable();
        buttonspanel = new javax.swing.JPanel();
        onebutton = new javax.swing.JButton();
        twobutton = new javax.swing.JButton();
        threebutton = new javax.swing.JButton();
        fourbutton = new javax.swing.JButton();
        fivebutton = new javax.swing.JButton();
        sixbutton = new javax.swing.JButton();
        eightbutton = new javax.swing.JButton();
        ninebutton = new javax.swing.JButton();
        sevenbutton = new javax.swing.JButton();
        zerobutton = new javax.swing.JButton();
        backspace = new javax.swing.JButton();
        decimalbutton = new javax.swing.JButton();
        inventorypanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        inventoryTable = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        subtotal = new javax.swing.JLabel();
        tax = new javax.swing.JLabel();
        total = new javax.swing.JLabel();
        subtotalfield = new javax.swing.JTextField();
        taxfield = new javax.swing.JTextField();
        totalfield = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        mop = new javax.swing.JLabel();
        amount = new javax.swing.JLabel();
        change = new javax.swing.JLabel();
        cashamount = new javax.swing.JTextField();
        changefield = new javax.swing.JTextField();
        paybutton = new javax.swing.JButton();
        removebutton = new javax.swing.JButton();
        resetbutton = new javax.swing.JButton();
        exitbutton = new javax.swing.JButton();
        mopbox = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1280, 635));
        setPreferredSize(new java.awt.Dimension(1280, 635));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        itemsOverview.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        itemsOverview.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item", "Quantity", "Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        itemsOverview.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_NEXT_COLUMN);
        itemsOverview.setRowHeight(30);
        jScrollPane1.setViewportView(itemsOverview);
        if (itemsOverview.getColumnModel().getColumnCount() > 0) {
            itemsOverview.getColumnModel().getColumn(0).setPreferredWidth(150);
            itemsOverview.getColumnModel().getColumn(1).setPreferredWidth(70);
            itemsOverview.getColumnModel().getColumn(2).setPreferredWidth(70);
        }

        javax.swing.GroupLayout overviewpanelLayout = new javax.swing.GroupLayout(overviewpanel);
        overviewpanel.setLayout(overviewpanelLayout);
        overviewpanelLayout.setHorizontalGroup(
            overviewpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(overviewpanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        overviewpanelLayout.setVerticalGroup(
            overviewpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(overviewpanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        buttonspanel.setPreferredSize(new java.awt.Dimension(180, 362));

        onebutton.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        onebutton.setText("1");
        onebutton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        onebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onebuttonActionPerformed(evt);
            }
        });

        twobutton.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        twobutton.setText("2");
        twobutton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        twobutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                twobuttonActionPerformed(evt);
            }
        });

        threebutton.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        threebutton.setText("3");
        threebutton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        threebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                threebuttonActionPerformed(evt);
            }
        });

        fourbutton.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        fourbutton.setText("4");
        fourbutton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        fourbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fourbuttonActionPerformed(evt);
            }
        });

        fivebutton.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        fivebutton.setText("5");
        fivebutton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        fivebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fivebuttonActionPerformed(evt);
            }
        });

        sixbutton.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        sixbutton.setText("6");
        sixbutton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        sixbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sixbuttonActionPerformed(evt);
            }
        });

        eightbutton.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        eightbutton.setText("8");
        eightbutton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        eightbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eightbuttonActionPerformed(evt);
            }
        });

        ninebutton.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        ninebutton.setText("9");
        ninebutton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ninebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ninebuttonActionPerformed(evt);
            }
        });

        sevenbutton.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        sevenbutton.setText("7");
        sevenbutton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        sevenbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sevenbuttonActionPerformed(evt);
            }
        });

        zerobutton.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        zerobutton.setText("0");
        zerobutton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        zerobutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zerobuttonActionPerformed(evt);
            }
        });

        backspace.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        backspace.setText("C");
        backspace.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        backspace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backspaceActionPerformed(evt);
            }
        });

        decimalbutton.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        decimalbutton.setText(".");
        decimalbutton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        decimalbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                decimalbuttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout buttonspanelLayout = new javax.swing.GroupLayout(buttonspanel);
        buttonspanel.setLayout(buttonspanelLayout);
        buttonspanelLayout.setHorizontalGroup(
            buttonspanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonspanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(buttonspanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(onebutton, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fourbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sevenbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(decimalbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(buttonspanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(buttonspanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(twobutton, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(threebutton, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(buttonspanelLayout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(fivebutton, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(sixbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 1, Short.MAX_VALUE))
                    .addGroup(buttonspanelLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(buttonspanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(zerobutton, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(eightbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(buttonspanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(buttonspanelLayout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(ninebutton, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, buttonspanelLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(backspace, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        buttonspanelLayout.setVerticalGroup(
            buttonspanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, buttonspanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(buttonspanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(onebutton, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(threebutton, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(twobutton, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(buttonspanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fourbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fivebutton, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sixbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(buttonspanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sevenbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eightbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ninebutton, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(buttonspanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(zerobutton, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(backspace, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(decimalbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(78, 78, 78))
        );

        inventoryTable.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        inventoryTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Product Name", "Quantity", "Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        inventoryTable.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_NEXT_COLUMN);
        inventoryTable.setRowHeight(30);
        inventoryTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                inventoryTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(inventoryTable);
        if (inventoryTable.getColumnModel().getColumnCount() > 0) {
            inventoryTable.getColumnModel().getColumn(0).setPreferredWidth(5);
            inventoryTable.getColumnModel().getColumn(2).setPreferredWidth(5);
            inventoryTable.getColumnModel().getColumn(3).setPreferredWidth(5);
        }

        javax.swing.GroupLayout inventorypanelLayout = new javax.swing.GroupLayout(inventorypanel);
        inventorypanel.setLayout(inventorypanelLayout);
        inventorypanelLayout.setHorizontalGroup(
            inventorypanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inventorypanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        inventorypanelLayout.setVerticalGroup(
            inventorypanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inventorypanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(overviewpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inventorypanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonspanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(buttonspanel, javax.swing.GroupLayout.DEFAULT_SIZE, 327, Short.MAX_VALUE)
                    .addComponent(inventorypanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(overviewpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        subtotal.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        subtotal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        subtotal.setText("SubTotal");

        tax.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        tax.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tax.setText("Tax");
        tax.setLocation(new java.awt.Point(-32750, -32261));

        total.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        total.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        total.setText("Total");

        subtotalfield.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        subtotalfield.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        taxfield.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        taxfield.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        totalfield.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        totalfield.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(subtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(subtotalfield, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(total, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(totalfield))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(tax, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(taxfield)))
                .addGap(18, 18, 18))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(subtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(subtotalfield, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tax, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(taxfield, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(total, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(totalfield, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        mop.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        mop.setText("Payment Method:");
        mop.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        amount.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        amount.setText("Amount:");
        amount.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        change.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        change.setText("Change:");
        change.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        cashamount.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N

        changefield.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N

        paybutton.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        paybutton.setText("PAY");
        paybutton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        paybutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paybuttonActionPerformed(evt);
            }
        });

        removebutton.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        removebutton.setText("REMOVE");
        removebutton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        removebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removebuttonActionPerformed(evt);
            }
        });

        resetbutton.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        resetbutton.setText("RESET");
        resetbutton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        resetbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetbuttonActionPerformed(evt);
            }
        });

        exitbutton.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        exitbutton.setForeground(new java.awt.Color(255, 0, 0));
        exitbutton.setText("EXIT");
        exitbutton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        exitbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitbuttonActionPerformed(evt);
            }
        });

        mopbox.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        mopbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cash", "GCash", "Maya", "Credit Card", "Debit Card" }));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(123, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(mop, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(mopbox, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(amount, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cashamount, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(change, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(changefield, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(removebutton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(resetbutton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(exitbutton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(paybutton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(mop, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(amount, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(change, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(changefield, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(paybutton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mopbox, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cashamount, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(removebutton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(resetbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(exitbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1100, 631));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void onebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onebuttonActionPerformed
        // TODO add your handling code here:
        String input = cashamount.getText();
        if (input == "") {
            cashamount.setText(onebutton.getText());
        } else {
            input = cashamount.getText() + onebutton.getText();
            cashamount.setText(input);
        }
    }//GEN-LAST:event_onebuttonActionPerformed

    private void twobuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_twobuttonActionPerformed
        // TODO add your handling code here:
        String input = cashamount.getText();
        if (input == "") {
            cashamount.setText(twobutton.getText());
        } else {
            input = cashamount.getText() + twobutton.getText();
            cashamount.setText(input);
        }
    }//GEN-LAST:event_twobuttonActionPerformed

    private void threebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_threebuttonActionPerformed
        // TODO add your handling code here:
        String input = cashamount.getText();
        if (input == "") {
            cashamount.setText(threebutton.getText());
        } else {
            input = cashamount.getText() + threebutton.getText();
            cashamount.setText(input);
        }
    }//GEN-LAST:event_threebuttonActionPerformed

    private void fourbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fourbuttonActionPerformed
        // TODO add your handling code here:
        String input = cashamount.getText();
        if (input == "") {
            cashamount.setText(fourbutton.getText());
        } else {
            input = cashamount.getText() + fourbutton.getText();
            cashamount.setText(input);
        }
    }//GEN-LAST:event_fourbuttonActionPerformed

    private void fivebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fivebuttonActionPerformed
        // TODO add your handling code here:
        String input = cashamount.getText();
        if (input == "") {
            cashamount.setText(fivebutton.getText());
        } else {
            input = cashamount.getText() + fivebutton.getText();
            cashamount.setText(input);
        }
    }//GEN-LAST:event_fivebuttonActionPerformed

    private void sixbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sixbuttonActionPerformed
        // TODO add your handling code here:
        String input = cashamount.getText();
        if (input == "") {
            cashamount.setText(sixbutton.getText());
        } else {
            input = cashamount.getText() + sixbutton.getText();
            cashamount.setText(input);
        }
    }//GEN-LAST:event_sixbuttonActionPerformed

    private void sevenbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sevenbuttonActionPerformed
        // TODO add your handling code here:
        String input = cashamount.getText();
        if (input == "") {
            cashamount.setText(sevenbutton.getText());
        } else {
            input = cashamount.getText() + sevenbutton.getText();
            cashamount.setText(input);
        }
    }//GEN-LAST:event_sevenbuttonActionPerformed

    private void eightbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eightbuttonActionPerformed
        // TODO add your handling code here:
        String input = cashamount.getText();
        if (input == "") {
            cashamount.setText(eightbutton.getText());
        } else {
            input = cashamount.getText() + eightbutton.getText();
            cashamount.setText(input);
        }
    }//GEN-LAST:event_eightbuttonActionPerformed

    private void ninebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ninebuttonActionPerformed
        // TODO add your handling code here:
        String input = cashamount.getText();
        if (input == "") {
            cashamount.setText(ninebutton.getText());
        } else {
            input = cashamount.getText() + ninebutton.getText();
            cashamount.setText(input);
        }
    }//GEN-LAST:event_ninebuttonActionPerformed

    private void zerobuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zerobuttonActionPerformed
        // TODO add your handling code here:
        String input = cashamount.getText();
        if (input == "") {
            cashamount.setText(zerobutton.getText());
        } else {
            input = cashamount.getText() + zerobutton.getText();
            cashamount.setText(input);
        }
    }//GEN-LAST:event_zerobuttonActionPerformed

    private void decimalbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_decimalbuttonActionPerformed
        // TODO add your handling code here:
        String input = cashamount.getText();
        if (input == "") {
            cashamount.setText(decimalbutton.getText());
        } else {
            input = cashamount.getText() + decimalbutton.getText();
            cashamount.setText(input);
        }
    }//GEN-LAST:event_decimalbuttonActionPerformed

    private void backspaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backspaceActionPerformed
        // TODO add your handling code here: 
        String currentText = cashamount.getText();
        if (currentText.length() > 0) {
            cashamount.setText(currentText.substring(0, currentText.length() - 1));
        }
    }//GEN-LAST:event_backspaceActionPerformed

    private void inventoryTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inventoryTableMouseClicked
        // TODO add your handling code here:
        int selectedRowIndex = inventoryTable.getSelectedRow();

        String productName = inventoryTable.getValueAt(selectedRowIndex, 1).toString();
        double price = Double.parseDouble(inventoryTable.getValueAt(selectedRowIndex, 3).toString());

        int quantity = 1;

        DefaultTableModel model = (DefaultTableModel) itemsOverview.getModel();

        boolean productExists = false;
        for (int i = 0; i < model.getRowCount(); i++) {
            String existingProductName = model.getValueAt(i, 0).toString();
            if (existingProductName.equals(productName)) {
                int existingQuantity = Integer.parseInt(model.getValueAt(i, 1).toString());
                double existingPrice = Double.parseDouble(model.getValueAt(i, 2).toString());
                int updatedQuantity = existingQuantity + quantity;
                double updatedPrice = existingPrice + (price * quantity); // Adjusted calculation
                model.setValueAt(updatedQuantity, i, 1);
                model.setValueAt(updatedPrice, i, 2);
                productExists = true;
                break;
            }
        }

        if (!productExists) {
            model.addRow(new Object[]{productName, quantity, price});
        }

        double subtotal = 0.0;
        for (int i = 0; i < model.getRowCount(); i++) {
            double itemPrice = Double.parseDouble(model.getValueAt(i, 2).toString());
            subtotal += itemPrice;
        }

        double taxRate = 0.10;
        double tax = subtotal * taxRate;

        double totalPrice = subtotal + tax;

        subtotalfield.setText(String.valueOf(subtotal));
        taxfield.setText(String.valueOf(tax));
        totalfield.setText(String.valueOf(totalPrice));
    }//GEN-LAST:event_inventoryTableMouseClicked

    private void paybuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paybuttonActionPerformed
        // TODO add your handling code here:
        String cashAmountText = cashamount.getText();
        if (cashAmountText.isEmpty()) {
            JOptionPane.showMessageDialog(null, "No payment received.");
        } else {
            double total = Double.parseDouble(totalfield.getText());
            double cashAmount = Double.parseDouble(cashAmountText);
            double change = cashAmount - total;
            changefield.setText(String.valueOf(change));

            if (cashAmount < total) {
                JOptionPane.showMessageDialog(null, "Invalid amount. The cash amount is less than the total.");
                return;
            }

            JOptionPane pane = new JOptionPane();
            pane.setMessage("Transaction successful.");
            pane.setOptionType(JOptionPane.DEFAULT_OPTION);
            pane.setOptions(new Object[]{"Print Receipt"});
            JDialog dialog = pane.createDialog(null, "Success");
            dialog.setVisible(true);

            Object selectedOption = pane.getValue();
            if (selectedOption != null && selectedOption.equals("Print Receipt")) {
            }
        }
    }//GEN-LAST:event_paybuttonActionPerformed

    private void removebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removebuttonActionPerformed
        // TODO add your handling code here:
        int selectedRow = itemsOverview.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel) itemsOverview.getModel();

        if (selectedRow != -1) {
            double removedPrice = Double.parseDouble(model.getValueAt(selectedRow, 2).toString());
            int removedQuantity = Integer.parseInt(model.getValueAt(selectedRow, 1).toString());

            model.removeRow(selectedRow);

            double subtotal = 0.0;
            for (int i = 0; i < model.getRowCount(); i++) {
                double itemPrice = Double.parseDouble(model.getValueAt(i, 2).toString());
                int itemQuantity = Integer.parseInt(model.getValueAt(i, 1).toString());
                subtotal += itemPrice * itemQuantity;
            }

            double taxRate = 0.10;
            double tax = subtotal * taxRate;
            double total = subtotal + tax;

            subtotalfield.setText(String.valueOf(subtotal));
            taxfield.setText(String.valueOf(tax));
            totalfield.setText(String.valueOf(total));
        }
    }//GEN-LAST:event_removebuttonActionPerformed

    private void resetbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetbuttonActionPerformed
        // TODO add your handling code here:
        dispose();
        pos main = new pos();
        main.setVisible(true);
    }//GEN-LAST:event_resetbuttonActionPerformed

    private void exitbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitbuttonActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Are you sure you want to Exit?", "WARNING", JOptionPane.WARNING_MESSAGE);
        dispose();
        signin signin = new signin();
        signin.setVisible(true);
    }//GEN-LAST:event_exitbuttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel amount;
    private javax.swing.JButton backspace;
    private javax.swing.JPanel buttonspanel;
    private javax.swing.JTextField cashamount;
    private javax.swing.JLabel change;
    private javax.swing.JTextField changefield;
    private javax.swing.JButton decimalbutton;
    private javax.swing.JButton eightbutton;
    private javax.swing.JButton exitbutton;
    private javax.swing.JButton fivebutton;
    private javax.swing.JButton fourbutton;
    private javax.swing.JTable inventoryTable;
    private javax.swing.JPanel inventorypanel;
    private javax.swing.JTable itemsOverview;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel mop;
    private javax.swing.JComboBox<String> mopbox;
    private javax.swing.JButton ninebutton;
    private javax.swing.JButton onebutton;
    private javax.swing.JPanel overviewpanel;
    private javax.swing.JButton paybutton;
    private javax.swing.JButton removebutton;
    private javax.swing.JButton resetbutton;
    private javax.swing.JButton sevenbutton;
    private javax.swing.JButton sixbutton;
    private javax.swing.JLabel subtotal;
    private javax.swing.JTextField subtotalfield;
    private javax.swing.JLabel tax;
    private javax.swing.JTextField taxfield;
    private javax.swing.JButton threebutton;
    private javax.swing.JLabel total;
    private javax.swing.JTextField totalfield;
    private javax.swing.JButton twobutton;
    private javax.swing.JButton zerobutton;
    // End of variables declaration//GEN-END:variables
}
